
import React, { createContext, useState, useContext, ReactNode } from 'react';

export type Language = 'fr' | 'en';

// Helper for pluralization or replacements
type TranslationReplacements = { [key: string]: string | number };

const translate = (key: string, lang: Language, translations: Record<Language, Record<string, string>>, replacements?: TranslationReplacements): string => {
    let text = translations[lang][key] || translations['en'][key] || key;
    if (replacements) {
        Object.keys(replacements).forEach(placeholder => {
            text = text.replace(new RegExp(`\\{${placeholder}\\}`, 'g'), String(replacements[placeholder]));
        });
    }
    return text;
};


// --- TRANSLATIONS ---

const translations: Record<Language, Record<string, string>> = {
  fr: {
    headerSubtitle: "Google Social Agent",
    reset: "Réinitialiser",
    methodology: "Méthodologie",
    help: "Aide",
    welcomeTitle: "Bienvenue sur G.S.A.",
    welcomeSubtitle: "Importez vos fichiers pour lancer une nouvelle analyse. La méthodologie et au moins un fichier de mentions sont requis.",
    earnedMentionsTitle: "Mentions EARNED",
    ownedMentionsTitle: "Mentions OWNED (Optionnel)",
    slrrMentionsTitle: "Daily SLRR Mentions (Optionnel)",
    methodologyTitle: "Méthodologie",
    dropShared: "Glissez-déposez le fichier",
    selectShared: "ou cliquez pour sélectionner",
    fileFormatsExcel: "Formats : .csv, .xls, .xlsx",
    fileFormatsZip: "Formats : .csv, .xls, .xlsx, .zip",
    fileFormatsPdf: "Format : .pdf",
    analysisSettings: "Paramètres de l'analyse",
    analysisSettingsEarned: "Filtres EARNED",
    analysisSettingsOwned: "Filtres OWNED",
    analysisSettingsSlrr: "Filtres SLRR",
    requiredFilesMessage: "* Au moins un des fichiers de mentions (EARNED, OWNED ou SLRR) est requis.",
    remove: "Supprimer",
    extractedFile: "Fichier extrait :",
    selectPlatforms: "Filtres & Méthodologie",
    selectAll: "Tout sélectionner",
    deselectAll: "Tout désélectionner",
    ignoreReplies: "Ignorer les réponses (tweets commençant par \"@\")",
    replace: "Remplacer",
    startAnalysis: "Lancer l'analyse sur {count} mention{plural}",
    startAnalysisDisabledTooltip: "Veuillez importer la méthodologie et au moins un fichier de mentions.",
    loading_analyzingBatch: "Analyse des mentions... Lot {current} sur {total}",
    loading_analyzing: "Analyse des mentions et tagging automatique...",
    loading_generating: "Génération des propositions de réponse...",
    loading_generating_progress: "Génération des réponses {start} à {end} sur {total}...",
    humanValidation: "Validation humaine",
    validationSubtitle: "L'IA a classé les mentions : {responseCount} à répondre, {likeCount} à liker et {modCount} à modérer.",
    tab_mentionsToReply: "Mentions à Répondre",
    tab_earned: "EARNED",
    tab_owned: "OWNED",
    tab_likeOnly: "Likes",
    bento_ownedTitle: "MENTIONS TO REPLY (OWNED)",
    bento_earnedTitle: "MENTIONS TO REPLY (EARNED)",
    bento_likeTitle: "MENTIONS TO LIKE",
    bento_moderationTitle: "MENTIONS TO HIDE / DELETE",
    modReason: "Raison de la modération :",
    likeReason: "Raison de l'IA :",
    generateResponses: "Générer les réponses ({count})",
    opportunityScore: "{score}/5",
    viewOriginal: "Voir la mention originale",
    generatedResponsesTitle: "Réponses générées",
    resultsPrompt: "Choisissez la meilleure réponse pour chaque mention, puis exportez votre sélection.",
    exportSelections: "Exporter la sélection ({count})",
    enthusiastic: "Enthousiaste",
    clever: "Astucieux",
    conversational: "Conversationnel",
    editResponse: "Modifier la réponse {label}",
    copyResponse: "Copier la réponse {label}",
    yourCustomResponse: "Votre réponse personnalisée",
    copyCustomResponse: "Copier la réponse personnalisée",
    customResponsePlaceholder: "Écrivez votre propre réponse ici ou améliorez-la avec l'IA...",
    magnifyWithAI: "Améliorer avec l'IA",
    magnifying: "Amélioration...",
    sharpenResponse: "Raccourcir la réponse",
    sharpening: "Raccourcissement...",
    regenerateHint: "Directives pour la régénération des 3 réponses ci-dessus...",
    adjustToneMatrix: "Ajuster la matrice tonale",
    regenerate: "Régénérer",
    regenerating: "En cours...",
    selected: "Sélectionnée",
    guidelinesPassed: "Cette mention respecte les guidelines Google.",
    guidelinesCheck: "Guidelines",
    exportViewTitle: "Exporter pour Google Sheets",
    exportViewSubtitle: "Le tableau ci-dessous est prêt. Cliquez pour copier les données et collez-les dans votre Google Sheet.",
    copyTable: "Copier le tableau",
    copied: "Copié !",
    backToResults: "Retour aux résultats",
    col_date: "Date",
    col_status: "Status",
    col_pa: "PA",
    col_platform: "Platform",
    col_source: "1P / 3P",
    col_userTag: "User Tag",
    col_userPost: "User post / comment",
    col_googleInteraction: "Google Interaction",
    col_proposedAnswer: "Proposed Answer",
    col_commentPMM: "Comment PMM",
    col_pm: "PM",
    col_commentCB: "Comment CB",
    col_cb: "CB",
    errorTitle: "Une erreur est survenue",
    errorUnknown: "Une erreur inconnue est survenue. Veuillez réessayer.",
    errorGoBack: "Recommencer",
    toneMatrixTitle: "Ajuster la Matrice Tonale",
    toneMatrixSubtitle: "Personnalisez la personnalité de l'IA pour la mention de <span class=\"font-semibold\">{author}</span>.",
    descriptor: "Descripteur",
    intensity: "Intensité (1-10)",
    contextActivation: "Contexte / Exemples d'activation",
    descriptorPlaceholder: "Ex: Amical",
    contextPlaceholder: "Ex: Pour répondre à une question simple",
    addDescriptor: "+ Ajouter un descripteur",
    cancel: "Annuler",
    regenerateWithMatrix: "Régénérer avec cette matrice",
    methodologyModalTitle: "Méthodologie (Prompt Système)",
    methodologyModalSubtitle: "Modifiez le prompt. Les changements seront appliqués à la prochaine génération.",
    methodologyPlaceholder: "Entrez ou collez votre méthodologie ici...",
    close: "Fermer",
    personalityCardTitle: "{name}",
    personalityCardSubtitle: "Profil de personnalité de l'IA",
    summary: "Résumé",
    traits: "Traits de caractère",
    dos: "À faire",
    donts: "À ne pas faire",
    chatToRefine: "Discuter pour affiner",
    chatPlaceholder: "Discute avec moi pour ajuster ma personnalité ! Par ex: \"Sois plus direct et moins formel\"",
    chatInputPlaceholder: "Ton message à G.S.A....",
    send: "Envoyer",
    applyChanges: "Appliquer les changements",
    updating: "Mise à jour...",
    geoGreeting1: "Coucou ! Prêt à m'ajuster ? ✨",
    geoGreeting2: "Hello ! On change ma personnalité ?",
    geoGreeting3: "Hey ! En quoi puis-je t'aider ? 😊",
    geoGreeting4: "Salut ! C'est moi, G.S.A. !",
    geoGreeting5: "J'ai une idée brillante ! 💡",
    geoGreeting6: "Hmm... à quoi je pense ?",
    geoGreeting7: "On s'amuse bien ! 🎉",
    personalityTabTitle: "Personnalité de l'IA",
    guidelinesTabTitle: "Guidelines Google",
    funnelSidebarTitle: "Funnel du Processus",
    funnel_uploaded: "Mentions Importées",
    funnel_total: "Total",
    funnel_earned: "Earned",
    funnel_owned: "Owned",
    funnel_slrr: "SLRR",
    funnel_shortlisted: "Présélection IA",
    funnel_forReplying: "Pour Réponse",
    funnel_forLiking: "Pour Like",
    funnel_forModeration: "A Modérer",
    funnel_generation: "Sélection pour Génération",
    funnel_repliesSelected: "Réponses finales",
    funnel_likesSelected: "Likes finaux",
    funnel_paBreakdown: "Répartition par PA",
    funnel_copyReport: "Copier le rapport",
    funnel_copied: "Copié !",
    funnel_reportTitle: "Rapport du Funnel",
    funnel_reportDate: "Date des Mentions",
    guidelinesModalTitle: "Guide de Community Management de Google",
    guidelinesModalSubtitle: "Référence extraite du document de méthodologie fourni.",
    howToUseTitle: "Comment utiliser G.S.A.",
    howToUseSubtitle: "Un guide étape par étape pour maîtriser l'outil.",
    howToUseStep1Title: "Importer vos fichiers",
    howToUseStep1Desc: "Le succès de G.S.A. repose sur la qualité de vos imports. Chaque fichier a un rôle précis :<br/><ul><li class='mb-2'><b>Mentions EARNED :</b> Le fichier principal de votre veille (ex: export Brandwatch). Il contient les conversations publiques sur votre marque. Formats supportés : .csv, .xls, .xlsx.</li><li class='mb-2'><b>Mentions OWNED (Optionnel) :</b> Les commentaires sur vos propres publications (ex: export Sprinklr). G.S.A. can analyze them separately. Formats supportés : .csv, .xls, .xlsx, ou un .zip contenant un fichier Excel.</li><li><b>Méthodologie :</b> C'est le fichier le plus important. Il s'agit de votre guide de community management en <b>.pdf</b>. L'IA l'apprend et l'utilise comme son cerveau pour toutes ses décisions : ton, style, règles de sécurité, etc.</li></ul>",
    howToUseStep2Title: "Configurer & Analyser",
    howToUseStep2Desc: "Avant de lancer l'IA, vous pouvez affiner les données à analyser :<ul><li class='mb-2'><b>Filtres par plateforme :</b> Décochez les plateformes que vous ne souhaitez pas inclure dans l'analyse.</li><li class='mb-2'><b>Filtre Twitter/X :</b> Pour les conversations Earned et Owned sur X, vous pouvez cocher la case pour ignorer les réponses directes (tweets commençant par '@'), afin de vous concentrer sur les tweets initiaux.</li></ul>Une fois prêt, cliquez sur <b>Lancer l'analyse</b>. G.S.A. va :<br/>1. Lire et comprendre votre méthodologie.<br/>2. Analyser chaque mention pour sa pertinence.<br/>3. Attribuer des tags de produits (Pixel, Search...).<br/>4. Calculer un score d'opportunité.<br/>5. Vérifier la conformité avec vos 'guidelines'.",
    howToUseStep3Title: "Human Validation",
    howToUseStep3Desc: "C'est l'étape de supervision. G.S.A. vous présente les mentions qu'il a jugées les plus intéressantes, classées en trois groupes :<br/><ul><li class='mb-2'><b>OWNED & EARNED:</b> Mentions pour lesquelles il recommande une réponse écrite. Examinez ses choix, ses tags et ses scores.</li><li class='mb-2'><b>Mentions pour LIKE:</b> Mentions positives qui ne nécessitent pas de réponse, mais un simple 'like'. L'IA explique son choix.</li></ul>Votre mission : <b>cliquez sur les cartes</b> que vous validez. Seules les mentions sélectionnées dans les sections OWNED et EARNED passeront à l'étape de génération de réponse.",
    howToUseStep4Title: "Generate & Refine Responses",
    howToUseStep4Desc: "C'est ici que la magie opère. Pour chaque mention validée, vous disposez d'un arsenal d'outils :<br/><ul><li class='mb-2'><b>Réponses Générées :</b> L'IA propose 3 à 4 réponses avec des tons différents. Vous pouvez les <b>modifier directement</b> dans leur case.</li><li class='mb-2'><b>Réponse Personnalisée :</b> Un espace pour écrire votre propre réponse ou utiliser l'IA pour l'améliorer avec le bouton <b>Améliorer</b> ✨.</li><li class='mb-2'><b>Outils d'Édition :</b> Sur chaque carte de réponse générée, vous pouvez <b>Raccourcir</b> ✂️ le texte pour plus de concision.</li><li class='mb-2'><b>Régénération Avancée :</b> Utilisez le champ 'Directives' pour donner un nouvel ordre à l'IA (ex: 'Sois plus drôle') et cliquez sur <b>Régénérer</b>. Vous pouvez aussi cliquer sur l'icône <b>sliders</b> 🎚️ pour ajuster finement la 'matrice tonale' pour cette mention spécifique avant de régénérer.</li></ul><b>Don't forget to click on the final response</b> (generated or custom) that you want to keep for the export.",
    howToUseStep5Title: "Exporter",
    howToUseStep5Desc: "L'étape finale ! Une fois que vous avez sélectionné une réponse pour chaque mention que vous souhaitez traiter, cliquez sur <b>Exporter la sélection</b>.<br/>Vous verrez un tableau pré-formaté avec toutes les données nécessaires pour votre suivi. Cliquez sur <b>Copier le tableau</b>. Le contenu est maintenant dans votre presse-papiers, prêt à être collé directement dans votre Google Sheet de suivi. C'est simple et rapide !",
    howToUseSpecialTitle: "Fonctionnalités Spéciales",
    howToUseSpecialDesc: "G.S.A. a des fonctionnalités puissantes accessibles à tout moment :<br/><ul><li class='mb-2'><b>AI Personality (Right Tab 🧠):</b> View the AI's complete personality card (traits, 'Dos & Don'ts'), extracted from your methodology. Even better, <b>chat with G.S.A.</b> to refine its personality. Ask it to be 'bolder' or 'more empathetic,' then click 'Apply Changes' to update its behavior for future generations.</li><li class='mb-2'><b>Guidelines (Left Tab 📖):</b> Quick access to the essential rules and guardrails from your methodology, so you never miss a thing.</li><li class='mb-2'><b>Methodology (Bottom Button):</b> View and edit the raw methodology text that the AI uses. Any changes here will affect the AI's next actions.</li></ul>",
    section1_title: "Section 1 : Introduction & Définition",
    section2_title: "Section 2 : Approche du Community Management @Google",
    section3_title: "Section 3 : Principes de Voix, Ton et Rédaction",
    section4_title: "Section 4 : Stratégie de Plateforme",
    section5_title: "Section 5 : Opérations et Flux de Travail",
    section6_title: "Section 6 : Directives d'Engagement et Garde-fous",
    section7_title: "Section 7 : Mesure et Impact",
    section8_title: "Section 8 : Annexe et Ressources",
    section9_title: "Section 9 : Instructions pour le Community Manager IA",
    error_503: "Le service IA est temporairement indisponible (Erreur 503). Veuillez patienter quelques instants et réessayer.",
    error_failedFileRead: "Erreur de lecture du fichier.",
    error_unsupportedFormat: "Format de fichier non supporté. Veuillez utiliser un fichier CSV, XLS ou XLSX.",
    error_zipRead: "Erreur de lecture du fichier ZIP. Il est peut-être corrompu.",
    error_noExcelInZip: "Aucun fichier Excel (.xls, .xlsx) trouvé dans l'archive ZIP.",
    error_csvParse: "Erreur lors du parsing CSV/TSV: {message}",
    error_excelRead: "Une erreur est survenue lors de la lecture du fichier Excel.",
    error_missingHeader: "Le fichier Brandwatch importé ne correspond pas au format attendu. Impossible de trouver la ligne d'en-tête.",
    error_missingHeaderOwned: "Le fichier Sprinklr importé ne semble pas valide. Impossible de trouver l'en-tête (recherche de 'Message' et 'SenderScreenName').",
    error_missingColumnOwned: "Le fichier Sprinklr doit contenir les colonnes 'UniversalMessageId', 'Message', et 'SenderScreenName'.",
    error_missingMentionColumn: "La colonne 'Mention' ou 'Full Text' est requise mais n'a pas été trouvée dans l'en-tête.",
    error_noValidMentions: "Aucune mention valide n'a été trouvée dans le fichier. Vérifiez que les données se trouvent après la ligne d'en-tête.",
    error_personalityAnalysisFailed: "L'analyse de la personnalité a échoué. La carte de personnalité ne sera pas disponible.",
    error_pdfRead: "Erreur lors de la lecture du fichier PDF. Assurez-vous qu'il n'est pas corrompu. Détails: {details}",
    error_noMentionsForFilters: "Aucune mention ne correspond aux filtres sélectionnés. Veuillez vérifier vos sélections de plateformes et de filtres.",
    error_regenerationFailed: "Erreur de régénération: {message}",
    error_magnifyFailed: "Erreur d'amélioration: {message}",
    error_sharpenFailed: "Le raccourcissement de la réponse a échoué : {message}",
    error_chatFailed: "Oups, petit bug ! Je n'arrive pas à répondre. Réessaye s'il te plaît ! 😵",
    error_updateFailed: "Erreur de mise à jour: {message}",
    error_methodologyAnalysisFailed: "L'analyse de la méthodologie a échoué. Certaines fonctionnalités basées sur l'IA pourraient ne pas être disponibles.",
  },
  en: {
    headerSubtitle: "Google Social Agent",
    reset: "Reset",
    methodology: "Methodology",
    help: "Help",
    welcomeTitle: "Welcome to G.S.A.",
    welcomeSubtitle: "Upload your files to start a new analysis. Methodology and at least one mention file are required.",
    earnedMentionsTitle: "EARNED Mentions",
    ownedMentionsTitle: "OWNED Mentions (Optional)",
    slrrMentionsTitle: "Daily SLRR Mentions (Optional)",
    methodologyTitle: "Methodology",
    dropShared: "Drag & Drop file",
    selectShared: "or click to select",
    fileFormatsExcel: "Formats: .csv, .xls, .xlsx",
    fileFormatsZip: "Formats: .csv, .xls, .xlsx, .zip",
    fileFormatsPdf: "Format: .pdf",
    analysisSettings: "Analysis Settings",
    analysisSettingsEarned: "EARNED Filters",
    analysisSettingsOwned: "OWNED Filters",
    analysisSettingsSlrr: "SLRR Filters",
    requiredFilesMessage: "* At least one mention file (EARNED, OWNED or SLRR) is required.",
    remove: "Remove",
    extractedFile: "Extracted file:",
    selectPlatforms: "Filters & Methodology",
    selectAll: "Select All",
    deselectAll: "Deselect All",
    ignoreReplies: "Ignore replies (tweets starting with \"@\")",
    replace: "Replace",
    startAnalysis: "Start Analysis on {count} mention{plural}",
    startAnalysisDisabledTooltip: "Please upload methodology and at least one mention file.",
    loading_analyzingBatch: "Analyzing mentions... Batch {current} of {total}",
    loading_analyzing: "Analyzing mentions and auto-tagging...",
    loading_generating: "Generating response proposals...",
    loading_generating_progress: "Generating responses {start} to {end} of {total}...",
    humanValidation: "Human Validation",
    validationSubtitle: "AI has classified mentions: {responseCount} to respond, {likeCount} to like and {modCount} to moderate.",
    tab_mentionsToReply: "Mentions to Reply",
    tab_earned: "EARNED",
    tab_owned: "OWNED",
    tab_likeOnly: "Likes",
    bento_ownedTitle: "MENTIONS TO REPLY (OWNED)",
    bento_earnedTitle: "MENTIONS TO REPLY (EARNED)",
    bento_likeTitle: "MENTIONS TO LIKE",
    bento_moderationTitle: "MENTIONS TO HIDE / DELETE",
    modReason: "Moderation reason:",
    likeReason: "AI reason:",
    generateResponses: "Generate Responses ({count})",
    opportunityScore: "{score}/5",
    viewOriginal: "View original mention",
    generatedResponsesTitle: "Generated Responses",
    resultsPrompt: "Choose the best response for each mention, then export your selection.",
    exportSelections: "Export Selection ({count})",
    enthusiastic: "Enthusiastic",
    clever: "Clever",
    conversational: "Conversational",
    editResponse: "Edit response {label}",
    copyResponse: "Copy response {label}",
    yourCustomResponse: "Your Custom Response",
    copyCustomResponse: "Copy custom response",
    customResponsePlaceholder: "Write your own response here or improve it with AI...",
    magnifyWithAI: "Magnify with AI",
    magnifying: "Magnifying...",
    sharpenResponse: "Shorten response",
    sharpening: "Shortening...",
    regenerateHint: "Directives for regenerating the 3 responses above...",
    adjustToneMatrix: "Adjust Tone Matrix",
    regenerate: "Regenerate",
    regenerating: "Generating...",
    selected: "Selected",
    guidelinesPassed: "This mention respects Google guidelines.",
    guidelinesCheck: "Guidelines",
    exportViewTitle: "Export for Google Sheets",
    exportViewSubtitle: "The table below is ready. Click to copy data and paste it into your Google Sheet.",
    copyTable: "Copy Table",
    copied: "Copied!",
    backToResults: "Back to Results",
    col_date: "Date",
    col_status: "Status",
    col_pa: "PA",
    col_platform: "Platform",
    col_source: "1P / 3P",
    col_userTag: "User Tag",
    col_userPost: "User post / comment",
    col_googleInteraction: "Google Interaction",
    col_proposedAnswer: "Proposed Answer",
    col_commentPMM: "Comment PMM",
    col_pm: "PM",
    col_commentCB: "Comment CB",
    col_cb: "CB",
    errorTitle: "An error occurred",
    errorUnknown: "An unknown error occurred. Please try again.",
    errorGoBack: "Start Over",
    toneMatrixTitle: "Adjust Tone Matrix",
    toneMatrixSubtitle: "Customize AI personality for <span class=\"font-semibold\">{author}</span>'s mention.",
    descriptor: "Descriptor",
    intensity: "Intensity (1-10)",
    contextActivation: "Context / Activation Examples",
    descriptorPlaceholder: "Ex: Friendly",
    contextPlaceholder: "Ex: To answer a simple question",
    addDescriptor: "+ Add descriptor",
    cancel: "Cancel",
    regenerateWithMatrix: "Regenerate with this matrix",
    methodologyModalTitle: "Methodology (System Prompt)",
    methodologyModalSubtitle: "Edit the prompt. Changes will be applied to the next generation.",
    methodologyPlaceholder: "Enter or paste your methodology here...",
    close: "Close",
    personalityCardTitle: "{name}",
    personalityCardSubtitle: "AI Personality Profile",
    summary: "Summary",
    traits: "Character Traits",
    dos: "Dos",
    donts: "Don'ts",
    chatToRefine: "Chat to Refine",
    chatPlaceholder: "Chat with me to adjust my personality! e.g., \"Be more direct and less formal\"",
    chatInputPlaceholder: "Your message to G.S.A....",
    send: "Send",
    applyChanges: "Apply Changes",
    updating: "Updating...",
    geoGreeting1: "Hi there! Ready to adjust me? ✨",
    geoGreeting2: "Hello! Shall we change my personality?",
    geoGreeting3: "Hey! How can I help you? 😊",
    geoGreeting4: "Hi! It's me, G.S.A.!",
    geoGreeting5: "I have a brilliant idea! 💡",
    geoGreeting6: "Hmm... what am I thinking?",
    geoGreeting7: "We're having fun! 🎉",
    personalityTabTitle: "AI Personality",
    guidelinesTabTitle: "Google Guidelines",
    funnelSidebarTitle: "Process Funnel",
    funnel_uploaded: "Imported Mentions",
    funnel_total: "Total",
    funnel_earned: "Earned",
    funnel_owned: "Owned",
    funnel_slrr: "SLRR",
    funnel_shortlisted: "AI Shortlist",
    funnel_forReplying: "For Reply",
    funnel_forLiking: "For Like",
    funnel_forModeration: "To Moderate",
    funnel_generation: "Selection for Generation",
    funnel_repliesSelected: "Final Replies",
    funnel_likesSelected: "Final Likes",
    funnel_paBreakdown: "PA Breakdown",
    funnel_copyReport: "Copy Report",
    funnel_copied: "Copied!",
    funnel_reportTitle: "Funnel Report",
    funnel_reportDate: "Mentions Date",
    guidelinesModalTitle: "Google Community Management Guide",
    guidelinesModalSubtitle: "Reference extracted from the provided methodology document.",
    howToUseTitle: "How to use G.S.A.",
    howToUseSubtitle: "A step-by-step guide to mastering the tool.",
    howToUseStep1Title: "Import your files",
    howToUseStep1Desc: "The success of G.S.A. relies on the quality of your imports. Each file has a specific role:<br/><ul><li class='mb-2'><b>EARNED Mentions:</b> The main file for your monitoring (e.g., Brandwatch export). It contains public conversations about your brand. Supported formats: .csv, .xls, .xlsx.</li><li class='mb-2'><b>OWNED Mentions (Optional):</b> Comments on your own posts (e.g., Sprinklr export). G.S.A. can analyze them separately. Supported formats: .csv, .xls, .xlsx, or a .zip containing an Excel file.</li><li><b>Methodology:</b> This is the most important file. It is your community management guide in <b>.pdf</b>. The AI learns it and uses it as its brain for all decisions: tone, style, safety rules, etc.</li></ul>",
    howToUseStep2Title: "Configure & Analyze",
    howToUseStep2Desc: "Before launching the AI, you can refine the data to analyze:<ul><li class='mb-2'><b>Platform filters:</b> Uncheck platforms you do not wish to include in the analysis.</li><li class='mb-2'><b>Twitter/X filter:</b> For Earned and Owned conversations on X, you can check the box to ignore direct replies (tweets starting with '@'), to focus on initial tweets.</li></ul>Once ready, click <b>Start Analysis</b>. G.S.A. will:<br/>1. Read and understand your methodology.<br/>2. Analyze each mention for relevance.<br/>3. Assign product tags (Pixel, Search...).<br/>4. Calculate an opportunity score.<br/>5. Check compliance with your 'guidelines'.",
    howToUseStep3Title: "Human Validation",
    howToUseStep3Desc: "This is the supervision step. G.S.A. presents the mentions it deemed most interesting, sorted into three groups:<br/><ul><li class='mb-2'><b>OWNED & EARNED:</b> Mentions for which it recommends a written response. Review its choices, tags, and scores.</li><li class='mb-2'><b>Mentions for LIKE:</b> Positive mentions that do not require a response, but a simple 'like'. The AI explains its choice.</li></ul>Your mission: <b>click on the cards</b> you validate. Only selected mentions in the OWNED and EARNED sections will proceed to the response generation step.",
    howToUseStep4Title: "Generate & Refine Responses",
    howToUseStep4Desc: "This is where the magic happens. For each validated mention, you have a toolkit:<br/><ul><li class='mb-2'><b>Generated Responses:</b> The AI proposes 3 to 4 responses with different tones. You can <b>edit directly</b> in their box.</li><li class='mb-2'><b>Custom Response:</b> A space to write your own response or use AI to improve it with the <b>Magnify</b> ✨ button.</li><li class='mb-2'><b>Editing Tools:</b> On each generated response card, you can <b>Shorten</b> ✂️ the text for conciseness.</li><li class='mb-2'><b>Advanced Regeneration:</b> Use the 'Directives' field to give a new order to the AI (e.g., 'Be funnier') and click <b>Regenerate</b>. You can also click the <b>sliders</b> 🎚️ icon to finely adjust the 'tone matrix' for this specific mention before regenerating.</li></ul><b>Don't forget to click on the final response</b> (generated or custom) that you want to keep for the export.",
    howToUseStep5Title: "Export",
    howToUseStep5Desc: "The final step! Once you have selected a response for each mention you want to handle, click <b>Export Selection</b>.<br/>You will see a pre-formatted table with all the necessary data for your tracking. Click <b>Copy Table</b>. The content is now in your clipboard, ready to be pasted directly into your tracking Google Sheet. Simple and fast!",
    howToUseSpecialTitle: "Special Features",
    howToUseSpecialDesc: "G.S.A. has powerful features accessible at any time:<br/><ul><li class='mb-2'><b>AI Personality (Right Tab 🧠):</b> View the AI's complete personality card (traits, 'Dos & Don'ts'), extracted from your methodology. Even better, <b>chat with G.S.A.</b> to refine its personality. Ask it to be 'bolder' or 'more empathetic,' then click 'Apply Changes' to update its behavior for future generations.</li><li class='mb-2'><b>Guidelines (Left Tab 📖):</b> Quick access to the essential rules and guardrails from your methodology, so you never miss a thing.</li><li class='mb-2'><b>Methodology (Bottom Button):</b> View and edit the raw methodology text that the AI uses. Any changes here will affect the AI's next actions.</li></ul>",
    section1_title: "Section 1: Introduction & Definition",
    section2_title: "Section 2: Community Management Approach @Google",
    section3_title: "Section 3: Voice, Tone and Writing Principles",
    section4_title: "Section 4: Platform Strategy",
    section5_title: "Section 5: Operations and Workflow",
    section6_title: "Section 6: Engagement Guidelines and Guardrails",
    section7_title: "Section 7: Measurement and Impact",
    section8_title: "Section 8: Appendix and Resources",
    section9_title: "Section 9: Instructions for AI Community Manager",
    error_503: "AI service is temporarily unavailable (Error 503). Please wait a moment and try again.",
    error_failedFileRead: "File read error.",
    error_unsupportedFormat: "Unsupported file format. Please use CSV, XLS or XLSX.",
    error_zipRead: "Error reading ZIP file. It may be corrupt.",
    error_noExcelInZip: "No Excel file (.xls, .xlsx) found in the ZIP archive.",
    error_csvParse: "Error parsing CSV/TSV: {message}",
    error_excelRead: "An error occurred while reading the Excel file.",
    error_missingHeader: "The imported Brandwatch file does not match the expected format. Unable to find the header row.",
    error_missingHeaderOwned: "The imported Sprinklr file does not seem valid. Unable to find header (searching for 'Message' and 'SenderScreenName').",
    error_missingColumnOwned: "The Sprinklr file must contain columns 'UniversalMessageId', 'Message', and 'SenderScreenName'.",
    error_missingMentionColumn: "The 'Mention' or 'Full Text' column is required but was not found in the header.",
    error_noValidMentions: "No valid mentions found in the file. Check that data is located after the header row.",
    error_personalityAnalysisFailed: "Personality analysis failed. The personality card will not be available.",
    error_pdfRead: "Error reading PDF file. Ensure it is not corrupt. Details: {details}",
    error_noMentionsForFilters: "No mentions match the selected filters. Please check your platform and filter selections.",
    error_regenerationFailed: "Regeneration error: {message}",
    error_magnifyFailed: "Improvement error: {message}",
    error_sharpenFailed: "Shortening response failed: {message}",
    error_chatFailed: "Oops, small bug! I can't reply. Please try again! 😵",
    error_updateFailed: "Update error: {message}",
    error_methodologyAnalysisFailed: "Methodology analysis failed. Some AI-based features might not be available.",
  }
};

export interface LocalizationContextType {
  language: Language;
  setLanguage: React.Dispatch<React.SetStateAction<Language>>;
  t: (key: string, replacements?: TranslationReplacements) => string;
}

const LocalizationContext = createContext<LocalizationContextType | undefined>(undefined);

export const LocalizationProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string, replacements?: TranslationReplacements) => {
    return translate(key, language, translations, replacements);
  };

  return React.createElement(
    LocalizationContext.Provider,
    { value: { language, setLanguage, t } },
    children
  );
};

export const useLocalization = () => {
  const context = useContext(LocalizationContext);
  if (!context) {
    throw new Error('useLocalization must be used within a LocalizationProvider');
  }
  return context;
};
